export type Testimonial = { name: string; age?: number; stars: number; text: string; tag?: string };

export const testimonials: Testimonial[] = [
  { name: "Ananya Mehra", age: 28, stars: 5, text: "“I booked a session mainly because I was confused about my career path. The conversation helped me organise my thoughts and look at a few things differently.”Ton of thanks to acharya aarti….." },
  { name: "Rohan Kapoor", age: 32, stars: 5, text: "“I had several questions before the consultation and got enough time to discuss them. Nothing felt rushed, which I appreciated.”" },
  { name: "Priya Sharma", age: 26, stars: 5, text: "First n for all thanks and gratitude to acharya aarti …“I was going through a confusing phase in my personal life. The session gave me some useful points to think about.”" },
  { name: "Arjun Malhotra", age: 35, stars: 5, text: "“I wanted guidance about work and future plans. The discussion was straightforward and easy for me to follow.”" },
  { name: "Sneha Verma", age: 30, stars: 5, text: "“I was able to speak openly about what had been bothering me. That made the session feel useful and relaxed.”" },
  { name: "Kunal Bhatia", age: 29, stars: 5, text: "“I had never tried anything like this before, so I was curious. It turned out to be an interesting experience.”" },
  { name: "Aditya Singh", age: 34, stars: 3, text: "“I went in with specific questions about my current situation. I liked being able to discuss each one properly.”most of them were answered and some of them were not due to lack of timings ." },
  { name: "Neha Arora", age: 27, stars: 4, text: "“The conversation gave me a chance to step back and think about things I had been ignoring for some time.”" },
  { name: "Vivek Khanna", age: 38, stars: 5, text: "“I found the overall session useful. The discussion stayed focused on the areas I wanted to explore.”" },
  { name: "Rahul Jain", age: 36, stars: 5, text: "“A good experience overall. I had time to ask what I wanted without feeling hurried.”" },
  { name: "Aditi Rao", age: 31, stars: 5, text: "“The consultation offered a refreshing lens through which to examine a period of uncertainty in my life. Several observations stayed with me long after the session ended.”" },
  { name: "Meera Iyer", age: 29, stars: 4, text: "“I valued the nuance of the conversation. Rather than receiving generic statements, I came away with several ideas worth contemplating.”thanks acharya aarti ji ." },
  { name: "Siddharth Nair", age: 33, stars: 5, text: "“There was a reassuring sense of structure throughout the discussion. My concerns were explored with care rather than treated superficially.”" },
  { name: "Kavya Menon", age: 25, stars: 5, text: "“What stood out was the balanced nature of the session. It gave me room to reflect without making me feel pressured toward a particular conclusion.”" },
  { name: "Dev Patel", age: 40, stars: 5, text: "“I approached the consultation with curiosity and left with a broader perspective on circumstances that had seemed somewhat tangled.”" },
  { name: "Nisha Desai", age: 27, stars: 4, text: "“The exchange was thoughtful and unexpectedly engaging. It encouraged me to reconsider a few assumptions I had been carrying for years.”Kudos acharya aarti" },
  { name: "Varun Bisht", age: 35, stars: 5, text: "“I appreciated the depth of attention given to my questions. The conversation unfolded in a measured way and never felt formulaic.”" },
  { name: "Rhea Rawat", age: 30, stars: 5, text: "“The session was particularly valuable during a transitional period for me. It helped bring certain priorities into sharper focus.”" },
  { name: "Manav Joshi", age: 28, stars: 5, text: "“I found the experience both absorbing and reflective. Some of the observations prompted a genuine reassessment of how I was approaching my next steps.”" },
  { name: "Tanya Bhardwaj", age: 32, stars: 5, text: "“Didn’t really know what to expect honestly, but the session was good. Some things made sense to me and gave me something to think about.”" },
  { name: "Harsh Vardhan", age: 37, stars: 5, text: "“Overall it was a nice experience. I had questions about work and family stuff and got to talk about them properly.”" },
  { name: "Simran Pal", age: 26, stars: 5, text: "“I was a little nervous before joining but after some time it felt quite easy. Good conversation and nice experience.”" },
  { name: "Vinamra Bajaj", age: 34, stars: 5, text: "“Wasnt sure before booking, but the session went better than I expected. A few things discussed were really worth thinking about.”" },
  { name: "Pooja Reddy", age: 39, stars: 4, text: "“The experience was good overall. I liked some parts more than others, but I did get a useful perspective from the conversation.”" },
  { name: "Yash Aggarwal", age: 31, stars: 3, text: "“Some things discussed matched what I was dealing with, while some points didnt connect much with me. Overall maybe around 70 percent felt relevant.”" },
  { name: "Kabir Taj", age: 28, stars: 5, text: "“Main mainly career ko lekar confused tha. Session ke baad aisa laga ki thoda ruk kar apne options ko dobara dekhna chahiye.”although  good soup served in session haha", tag: "Hinglish" },
  { name: "Isha Mallick", age: 33, stars: 5, text: "“Mere liye sabse achhi baat yeh rahi ki main bina kisi hesitation ke apni baat rakh paayi. Conversation kaafi natural rahi.”", tag: "Hinglish" },
  { name: "Arnav Shukla", age: 30, stars: 5, text: "“Life mein kuch decisions ko lekar confusion chal raha tha. Session ke baad at least thoughts thode sorted feel huye.”", tag: "Hinglish" },
  { name: "Diya Kapoor", age: 23, stars: 4, text: "“Experience achha raha aur kaafi cheezein discuss karne ko mili. Kuch points mujhe immediately samajh aaye, kuch par baad mein socha.”", tag: "Hinglish" },
  { name: "Simran Kaur", age: 26, stars: 5, text: "“Main personal life aur relationship ko lekar kaafi confused thi. Discussion ke baad situation ko thoda different angle se dekhne ka chance mila.”", tag: "Hinglish" },
  { name: "Sanya Mishra", stars: 4, text: "Idk about astrologer and other websites or app but this astrology and acharya aarti is a massive help for me btw this was my 2nd meet with her ." },
  // GenZ
  { name: "Preksha Nailwal", age: 21, stars: 5, text: "“Okay ngl, I went in with zero expectations but some of the things discussed actually made me pause and think. The whole session was a vibe.”", tag: "GenZ" },
  { name: "Aarav Singh", age: 23, stars: 5, text: "“Lowkey wasn’t expecting such a detailed session. Got to discuss stuff I’d been overthinking for ages lol. Definitely interesting.”", tag: "GenZ" },
  { name: "Ananya Gupta", age: 20, stars: 5, text: "“Not me getting called out by my own life patterns The session gave me a lot to think about, especially with college and career stuff.”", tag: "GenZ" },
  { name: "Vivaan Jamwal", age: 24, stars: 5, text: "“I’m usually the type who needs things explained properly, and honestly, this was easy to follow. No unnecessary complicated talk. Pretty solid experience.”", tag: "GenZ" },
  { name: "Isha Verma", age: 22, stars: 5, text: "“Okay but why did certain parts feel so relatable I came in confused and left with way more things to reflect on. The vibe was also super chilll.”", tag: "GenZ" },
  { name: "Kiara saxena", age: 23, stars: 4, text: "“Main toh bas curious thi but this turned out to be genuinely interesting Some points had me like ‘waittt how does that make sense?’ in the best way and also some points were tough for me to understand aswell.”", tag: "GenZ" },
  { name: "Reyansh Jain", age: 21, stars: 4, text: "“Pretty different from what I expected tbh. Had a lot of questions and didn’t feel judged for asking any of them. 8/10 for the overall experience.”", tag: "GenZ" },
  { name: "Adhya Sethi", age: 24, stars: 5, text: "“Honestly, I needed a fresh perspective and this session gave me exactly that. Not saying I suddenly have life figured out lol, but definitely got some clarity.”", tag: "GenZ" },
  { name: "Advik Bansal", age: 20, stars: 5, text: "“Went in thinking it would be a regular conversation but nope ended up discussing things I hadn’t really thought about before. Actually a pretty cool experience.”", tag: "GenZ" },
  { name: "Arjun Mehta", age: 19, stars: 5, text: "“Was lowkey confused about where things were going with someone I liked. Didn’t expect the conversation to make me think this much lol.”", tag: "GenZ" },
];
